# Generated by Django 3.2.8 on 2021-10-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
