# Generated by Django 3.2.8 on 2021-10-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
